##### THIS ALLOWS US TO DEPLOY THE SITE FROM A GIT REPO ######
—deployment:
Tasks:
– export DEPLOYPATH=/home/tanquema/public_html/
– /bin/cp -R .vscode $DEPLOYPATH
– /bin/cp -R assets $DEPLOYPATH
– /bin/cp -R css $DEPLOYPATH
– /bin/cp -R fonts $DEPLOYPATH
– /bin/cp -R img $DEPLOYPATH
– /bin/cp -R js $DEPLOYPATH
/bin/cp index.html $DEPLOYPATH
/bin/cp politicacookies.html $DEPLOYPATH
/bin/cp politicadeprivacidade.html $DEPLOYPATH
/bin/cp termoscondicoes.html $DEPLOYPATH
